"""
Bootstrap helpers for the External Secrets Operator (ESO).

ESO is a cluster-level, one-time install — it is NOT part of the
per-service deploy pipeline (see pipeline/stages/deploy.py). A given
cluster only needs it installed once, after which every environment's
`eso/` manifests (generated by Terraform — infra/modules/eso-manifests)
can sync secrets from AWS Secrets Manager into real k8s Secrets, e.g.
{{SERVICE_NAME}}-db-secret consumed by deployment.yaml.tpl.

This module intentionally does not run automatically as part of
`stackbridge service deploy` — installing/upgrading a cluster-wide
operator on every deploy is unsafe and unnecessary. Call it explicitly
via `stackbridge environment bootstrap-secrets`.
"""
import shutil
import subprocess
import time
from pathlib import Path

import click

ESO_NAMESPACE = "external-secrets-system"
ESO_HELM_REPO_NAME = "external-secrets"
ESO_HELM_REPO_URL = "https://charts.external-secrets.io"
ESO_RELEASE_NAME = "external-secrets"


class EsoError(Exception):
    pass


def _require_binaries():
    for binary in ("helm", "kubectl"):
        if shutil.which(binary) is None:
            raise EsoError(f"{binary} is not installed.")


REQUIRED_CRDS = (
    "externalsecrets.external-secrets.io",
    "secretstores.external-secrets.io",
)


def eso_installed():
    """
    Return True only if BOTH the operator pods AND its CRDs are
    present. Checking pods alone gives false positives if a prior
    install crashed, was run with --skip-crds, or otherwise left
    pods running without the CRDs registered (which produces
    'no matches for kind ExternalSecret ... ensure CRDs are
    installed first' when applying manifests).
    """

    pods = subprocess.run(
        ["kubectl", "get", "pods", "-n", ESO_NAMESPACE],
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
    )
    if pods.returncode != 0:
        return False

    for crd in REQUIRED_CRDS:
        crd_check = subprocess.run(
            ["kubectl", "get", "crd", crd],
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
        )
        if crd_check.returncode != 0:
            return False

    return True


def install_eso():
    """Install the External Secrets Operator via Helm (idempotent)."""

    _require_binaries()

    if eso_installed():
        click.echo("✓ external-secrets already installed, skipping")
        return

    click.echo("Installing External Secrets Operator...")

    subprocess.run(
        ["helm", "repo", "add", ESO_HELM_REPO_NAME, ESO_HELM_REPO_URL],
        check=True,
    )
    subprocess.run(["helm", "repo", "update"], check=True)

    # upgrade --install (not plain install) so this also repairs a
    # cluster left in the "pods exist, CRDs don't" half-installed
    # state. installCRDs=true is set explicitly rather than relying
    # on the chart's default, in case that default ever changes.
    subprocess.run(
        [
            "helm", "upgrade", "--install", ESO_RELEASE_NAME,
            f"{ESO_HELM_REPO_NAME}/external-secrets",
            "--namespace", ESO_NAMESPACE,
            "--create-namespace",
            "--set", "installCRDs=true",
        ],
        check=True,
    )

    click.echo("Waiting for ESO CRDs to become available...")
    for crd in REQUIRED_CRDS:
        subprocess.run(
            [
                "kubectl", "wait", "--for", "condition=Established",
                f"crd/{crd}", "--timeout", "60s",
            ],
            check=True,
        )

    click.echo("✓ external-secrets installed")


def apply_eso_manifests(eso_dir, retries=3, retry_delay=5):
    """
    Apply the Terraform-rendered eso/ manifests (SecretStore,
    ExternalSecret, ServiceAccount) for a given environment.

    eso_dir must already exist — it is produced by
    `terraform apply` against infra/modules/eso-manifests, NOT by
    `stackbridge scaffold`. Run that first.

    Retries on failure because kubectl caches API discovery info
    locally (~/.kube/cache/discovery). Even after a CRD reaches
    condition=Established server-side, the *client's* cache can
    still be stale on the very next invocation, producing a
    spurious "no matches for kind ExternalSecret ... ensure CRDs
    are installed first" even though the CRD is genuinely there.
    `kubectl apply` itself refreshes/invalidates its discovery
    cache when it hits a cache miss, so a short-delay retry is
    sufficient — no need to manually clear the cache directory.
    """

    _require_binaries()

    eso_path = Path(eso_dir)

    if not eso_path.is_dir():
        raise EsoError(
            f"{eso_path} does not exist. Run `terraform apply` for this "
            "environment's eso-manifests module first."
        )

    click.echo(f"Applying eso manifests from {eso_path}...")

    last_error = None

    for attempt in range(1, retries + 1):
        result = subprocess.run(
            ["kubectl", "apply", "-f", str(eso_path)],
            capture_output=True,
            text=True,
        )

        if result.returncode == 0:
            click.echo(result.stdout)
            click.echo("✓ eso manifests applied")
            return

        last_error = result.stderr

        if "ensure CRDs are installed first" in result.stderr and attempt < retries:
            click.echo(
                f"kubectl discovery cache looks stale (attempt {attempt}/"
                f"{retries}), retrying in {retry_delay}s..."
            )
            time.sleep(retry_delay)
            continue

        break

    raise EsoError(
        f"kubectl apply failed after {retries} attempt(s):\n{last_error}"
    )
