apiVersion: external-secrets.io/v1
kind: SecretStore

metadata:
  name: stackbridge-secret-store
  namespace: dev

spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        jwt:
          serviceAccountRef:
            name: stackbridge-eso-sa
