apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stackbridge-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/stackbridge/stackbridge
    targetRevision: HEAD
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: stackbridge
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
