# {{SERVICE_NAME}}

Generated by StackBridge.

## Run locally

```bash
docker build -t {{SERVICE_NAME}} .
docker run -p {{PORT}}:{{PORT}} {{SERVICE_NAME}}
kubectl apply -f k8s/
helm install {{SERVICE_NAME}} helm/
