apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: stackbridge

spec:

  rules:

  - host: stackbridge.local

    http:

      paths:

      - path: /

        pathType: Prefix

        backend:

          service:

            name: stackbridge

            port:

              number: 80
